---
title: Estudo da mortalidade por neoplasias malignas de trabalhadores de uma companhia hidrelétrica no período de 1985 a 2011.
author:
  - name: Lucas Rabelo
    affiliation: Affiliation
    address:
    - line 1
    - line 2
    email:  author1@work
  - name: Gecynalda Gomes
    affiliation: Affiliation
    address:
    - line 1
    - line 2
    email:  author2@work
abstract: >
 After a paper published in 1979 by Wertheimer and Leeper have shown a positive association between extremely low-frequency magnetic fields (elf-mf) and infant leukemia, studies investigating the risks between the exposure to elf-mf and the development of diseases subsequently caused the classification of exposure to these fields as 2B (Possibly carcinogenic) by IARC. This study aims to analyze deaths by malignant neoplasia and the risks that occupational exposure to elf-mf may have as a co-carcinogenic or carcinogenic factor, in a hydroelectric power facility located in Brazil. A database of 1253 deceased workers from 1985 until 2011, where 249 were identified as exposed to electricity and 995 were not, was used to evaluate the MOR, which was calculated accordingly to the exposure to elf-mf for those who died from malignant neoplasia, a bootstrap method was used to lower the range of the confidence intervals and bring more reliable estimates to the chosen statistic, a database of those who died by cancer in the country was gathered from a Brazilian information system powered by INCA to compare the MOR by sex and age within the company and the country. When using the traditional method to calculate the MOR, an elevated MOR was found for esophagus cancer*(MOR=5,50; CI=1,06-28,33; P=0,0235)*, whereas in the bootstrap method the MOR was high for the following cancer types: Esophagus*(MORBoot=6,73; CI=1,74- 16,67; P<0,0001)*, Non Hodgkin Lymphoma*(MORBoot=6,03; CI=2,62-10,81; P<0,0001)*, Bladder*(MORBoot=6,03; CI=2,62-10,81; P<0,0001)* and Bone*(MORBoot=3,95; CI=2,62-5,26; P<0,0001)*. Some limitations of the study, such as the lack of information about the lifestyle of the workers and the small number of cases, make more difficult to consider exposure to elf-mf as a carcinogenic or co-carcinogenic factor, but despite the limitations in this study, the elevated MORs and BootMORs  should be taken seriously requiring further research and better-funded studies in the area.
 

output: rticles::rjournal_article
---
### Keywords: *Hydroelectric, Cancer, Mortality Odds Ratio, Bootstrap, Statistic.*



```{r setup, include=FALSE}

library(rticles)

```


**Resumo:** Depois da publicação de um artigo por Wertheimer e Leeper em 1979 ter demonstrado uma associação positiva entre a exposição a campos eletromagnéticos de baixa frequência(CEM) e leucemia infantil, subsequentemente estudos investigando a exposição a tais campos e o desenvolvimento de doenças, levaram a classificação dos mesmos para 2B(possivelmente carcinogênicos) pela IARC. Esse estudo tem como objetivo analisar mortes por neoplasia maligna em uma companhia hidrelétrica brasileira e os possiveis riscos que a exposição ocupacional a CEM possa ter como fator carcinogênico ou co-carcinogênico. Um banco de dados de 1235 trabalhadores falecidos entre 1985 e 2011, onde 249 foram identificados como expostos e 995 não, foi utilizado para avaliar a MOR a qual foi calculada de acordo com a exposição para os que morreram por neoplasia maligna, um método bootstrap foi utilizado para trazer uma estimativa mais confiável para a estatística escolhida e diminuir a amplitude dos intervalos de confiança, um banco de dados da população brasileira falecida por câncer disponibilizado por um sistema e informações do INCA também foi utilizado para comparar a MOR da hidrelétrica e do país. Ao utilizar o método tradicional para cálculo da MOR, uma medida elevada foi achada para o câncer de esôfago*(MOR=5,50; IC=1,06-28,33; P=0,0235)*, enquanto no método bootstrap foi elevada para os seguintes tipos de câncer: Esôfago*(MORBoot=6,73; IC=1,74- 16,67; P<0,0001)*, Linfoma Não Hodgkin*(MORBoot=6,03; IC=2,62-10,81; P<0,0001)*, Bexiga*(MORBoot=6,03; IC=2,62-10,81; P<0,0001)* e Osso*(MORBoot=3,95; IC=2,62-5,26; P<0,0001)*. Algumas limitações do estudo como a falta de informação sobre os hábitos dos trabalhadores e o baixo número de casos, tornam mais complicado considerar a exposição aos CEM como um fator co-carcinogênico ou carcinogênico, porém apesar de tais limitações as elevadas MORs e BootMORs devem ser levadas a sério, exigindo mais estudos de maior escala na área.

### Palavras-chave: *Hidrelétrica, Câncer, Mortality Odds Ratio, Bootstrap, Estatística.*

# Introdução
 
 Visto que a intensidade de exposição ao CEM(campos eletromagnéticos de baixa frequência) em certos tipos de ocupações podem ser consideravelmente superiores a exposição residencial $\!\!^4$, após o marco de 1979 $\!\!^4$ \ $\!\!^5$ em que Wertheimer e Leeper trouxeram tal problemática a público ao demonstrar uma associação positiva entre o risco de leucemia infantil e a exposição a CEM, é pertinente a realização de estudos avaliando os possíveis riscos que tal exposição possa causar, principalmente após a IARC(Agência Internacional de Pesquisa em Câncer) $\!\!^2$ no ano de 2002 ter classificado os CEM como possivelmente carcinogênicos no grupo 2B $\!\!^4$ \ $\!\!^7$ \ $\!\!^9$, porém com evidências inadequadas para os outros tipos de câncer $\!\!^7$, no presente momento a classificação dada a IARC para os CEM é de 3(não classificado quanto a carcinogenicidade para humanos) $\!\!^2$. 
 
 Câncer de mama $\!\!^9$, próstata $\!\!^3$, cérebro $\!\!^7$ e leucemia $\!\!^1$ $\!\!^3$ foram apenas algumas das neoplasias que tiveram seu estudo direcionado a problemática da exposição aos CEM, entretanto poucos estudos sobre o tema foram realizados no Brasil, até o ano de 2009, segundo Marcílio, Habermann e Gouveia(2009, p.6), "apenas 4 estudos foram conduzidos na América Latina, 3 no Brasil e 1 no México" $\!\!^4$. Entretanto, a maioria dos resultados sobre a associação entre exposição ocupacional a campos eletromagnéticos e neoplasias malignas ainda é muito nebulosa, portanto os artigos preferem seguir a hipótese de que a exposição a campos eletromagnéticos de baixa frequência auxiliam no agravamento do quadro do paciente agindo como fatores co-carcinogênicos $\!\!^4$ \ $\!\!^5$ \ $\!\!^1\!^0$.
 
 Em um estudo realizado na Romênia $\!\!^3$ os indivíduos que foram empregados em diversos setores de suprimento, dentre os quais o de energia elétrica, apresentaram um maior risco para o câncer de próstata, afirmando que tal achado é similar a outros reportados em estudos de caso controle para plantas de geração de energia hidrelétrica, e pelo fato de redes de transmissão e geração de energia elétrica serem classificadas como CEM $\!\!^4$, tal afirmativa motiva o objetivo deste estudo, o qual será analisar a mortalidade por câncer em trabalhadores de uma companhia hidrelétrica brasileira e buscar por estatísticas e métodos que junto com os estudos anteriores possam dar suporte aos vindouros que abordarem a temática.    





# Metodologia

 O banco de dados consiste de 1.253 observações coletadas no período de 1985 até 2011, referentes ao diagnóstico de óbito em empregados, de uma companhia hidrelétrica brasileira, a qual por questões de privacidade não será identificada, dentre os empregados 1.130 foram do sexo masculino e 123 do feminino. O foco do estudo no entanto, está em um total de 254 indivíduos(39 do sexo feminino e 215 do masculino), em que a causa principal de falecimento se deu por neoplasia maligna, dos quais 209 foram classificados como não expostos e um total de 42 como afetados pela exposição, em toda a hidrelétrica 241 trabalhadores foram classificados como expostos em contrapartida a 995 não expostos. Devido a falta de informações sobre o estilo de vida dos trabalhadores e a dificuldade para medir a exposição $\!\!^4$ \ $\!\!^5$ \ $\!\!^1$ $\!\!^3$, é comum que estudos utilizem as ocupações $\!\!^5$ para realizar a classificação referente a exposição aos CEM, assim como nesse estudo em que os empregados foram classificados de forma binária, quanto a exposição.
 
 Para verificar o comportamento do óbito por neoplasia e exposição a eletricidade, foi calculada a MOR $\!\!^5$ \ $\!\!^6$ (Mortality Odds Ratio), a qual parafraseando Miettinen e Wang(1980, p.146, tradução nossa)" é obtida pela razão das chances de exposição pela causa de óbito", como o software R(versão 3.6.1) foi utilizado para o cálculo da citada estatística, vale ressaltar que para calcular a mesma foi usada a função que calcula as odds ratios, presente na biblioteca FMSB $\!\!^1\!^2$, o nível de confiança a ser considerado neste artigo é de 95%.
 
 Para a análise do comportamento de óbito por neoplasia e a exposição a eletricidade, houve a criação de três grupos, o Grupo A contendo todos os trabalhadores que foram a óbito por neoplasia expostos a eletricidade (40 do sexo masculino e 2 do feminino), o Grupo B com os trabalhadores não expostos que foram a óbito por neoplasia e alocados numa área de alta periculosidade (22 do sexo masculino) e o Grupo C contendo os trabalhadores que foram a óbito por neoplasia sem contato direto com eletricidade e que desempenhavam ocupações de baixa periculosidade(150 do sexo masculino e 37 do feminino). Também foi utilizado um método *bootstrap*, inspirado no proposto por Itskovich e Roudebush $\!\!^1$ $\!\!^4$, este método foi aplicado com 10.000 reamostragens no grupo A e em todos os indivíduos que faleceram por câncer e não possuiam contato com a eletricidade independentemente da periculosidade do trabalho realizado. 
 
 Na tentativa de identificar anomalias nas chances de óbito da hidrelétrica, houve a comparação entre a MOR da hidrelétrica e da população brasileira que foi a óbito por neoplasia maligna no período de 1985 até 2012, período este utilizado devido a leve presença de trabalhadores que tiveram o óbito registrado em tal ano, os dados para o Brasil estão disponibilizados na base de dados do INCA(Instituto Nacional do Câncer) $\!\!^1$ $\!\!^1\!^1$, a sigla MORH foi utilizada para se referir a MOR da hidrelétrica e MORB a da parcela da população brasileira conveniente para comparação, a análise comparativa foi feita considerando o sexo e as faixas etárias de óbito dos trabalhadores.
 
 
 
 
 
 

# Resultados

# Discussão

# Conclusão

# Referências


1. FARIA, Marcília de A M; Almeida, José Wilson R; Zanetta, Dirce M T. Mortalidade por câncer na
região urbano-industrial da Baixada Santista, SP (Brasil). Revista de Saúde Pública. São Paulo:
Universidade de São Paulo, Volume 33, Número 3, p.255-61. 1999.

2. [IARC] Iarc monographs on the identification of carcinogenic hazards to humans. Agents Classified
by the IARC Monographs, Volumes 1-125, 29/11/2019. Disponível em:
<https://monographs.iarc.fr/list-of-classifications/>. Acesso em: 08/12/2019.

3. Mateș, Dana; Calotă, Violeta Claudia, Oțelea, Marina Ruxandra. et al. Prostate cancer: an
occupational hazard in Romania?.Romanian Journal of Occupational Medicine. Romania. Volume 70,
N° 1, p.38-45. 2019.

4. Marcilio, Izabel; Habermann, Mateus; Gouveia, Nelson. Extremely low-frequency magnetic fields
and health effects: literature review. Revista Brasileira de Epidemiologia. Universidade de São Paulo:
Faculdade de Medicina, Volume 12, Número 2, p.1-19. 2009.

5. Mattos, Inês E.; Koifman Sérgio. Mortalidade por câncer em trabalhadores de companhia geradora
de eletricidade do Estado de São Paulo, Brasil. Rev. Saúde Pública. Rio de Janeiro: FIOCRUZ,
Volume 30, Número 6, p. 564-575. 1996.

6. MIETTINEN, OLLI S.; WANG, JUNG-DER. An alternative to the proportionate mortality ratio.
American Journal of Epidemiology. USA: The Johns Hopkins University School of Hygiene and
Public Health, Volume 114, N° 1, p. 144-148. 1981.

7. Turner, Michelle C.; Benke, Geza; Bowman, Joseph D. et al. Occupational exposure to extremely
low frequency magnetic fields and brain tumour risks in the INTEROCC study. Cancer Epidemiol
Biomarkers Prev. [S.l.], Volume 23, N° 9, p. 1863-1872. 2014.

8. Sorahan T. M. Cancer incidence in UK electricity generation and transmission workers,
1973–2015. Occupational Medicine. UK: University of Birmingham, Volume 69, N° 5, p. 342-351. 2019.

9. Grundy, Anne; Harris, Shelley A.; Demers, Paul A. et al. Occupational exposure to magnetic fields
and breast cancer among Canadian men. Cancer Medicine. Canada: Canadian Cancer Registries
Epidemiology Research Group, Volume 5, N° 3, p. 586-596. 2016.

10. Håkansson, N.; Floderus, B.; Gustavsson, P. et al. Cancer incidence and magnetic field exposure
in industries using resistance welding in Sweden. occup environ med. Sweden: Karolinska Institutet,
Volume 59, N° 7, p. 481-486. 2002.

11. [INCA] Atlas On-line de Mortalidade. Mortalidade-INCA, c1996. Tabulador. Disponível em:
<https://mortalidade.inca.gov.br/MortalidadeWeb/>. Acesso em: 08/12/2019.

12. Nakazawa, Minato. fmsb: Functions for Medical Statistics Book with some Demographic Data.
CRAN-R, 2018. Disponível em: <https://cran.r-project.org/web/packages/fmsb/index.html>. Acesso
em: 08/12/2019.

13. Marcílio, Izabel; Gouveia, Nelson; Filho, Mário L. P. et al. Adult mortality from leukemia, brain cancer, amyotrophic lateral sclerosis and magnetic fields from power lines: a case-control study in Brazil. Revista Brasileira de Epidemiologia. São Paulo: Universidade de São Paulo,Volume 14, N° 4, p. 580-588. 2011.

14. Itskovich I.; Roudebush B. Using re-sampling methods in mortality studies. PLoS One.United States of America, Volume 5, N°8, p. 1-6. 2010.

# Anexo
